export const recentChats = [
	{
		id: 1,
		image: "https://api.dicebear.com/5.x/personas/svg?seed=Bella&backgroundColor=fac248",
		name: "Killan James",
		date: "4:30 PM",
		isTyping: true,
		isOnline: true,
		unreadQuantity: 2,
	},
	{
		id: 2,
		image: "https://api.dicebear.com/5.x/icons/svg?seed=Socks",
		name: "Design Team",
		message: "Awesome 🔥",
		date: "9:36 AM",
		readMessage: true,
		isOnline: false,
	},
	{
		id: 3,
		image: "https://api.dicebear.com/5.x/personas/svg?seed=Abby&backgroundColor=ebbf9a",
		name: "Ahmed Medi",
		message: "Wow really Cool 🔥",
		date: "1:15 AM",
		isOnline: false,
	},
];

export const allChats = [
	{
		id: 1,
		image: "https://api.dicebear.com/5.x/personas/svg?seed=Angel&backgroundColor=eda0a8",
		name: "Claudia Maudi",
		date: "4:30 PM",
		isTyping: true,
		isOnline: true,
	},
	{
		id: 2,
		image: "https://api.dicebear.com/5.x/personas/svg?seed=Trouble&backgroundColor=aa98ca",
		name: "Novita",
		message: "yah, nice design",
		date: "4:30 PM",
		isOnline: true,
		unreadQuantity: 2,
	},
	{
		id: 3,
		image: "https://api.dicebear.com/5.x/personas/svg?seed=Misty&backgroundColor=5d6c67",
		name: "Ikhsan SD",
		isVoiceMessage: true,
		date: "yesterday",
		isOnline: false,
	},
	{
		id: 4,
		image: "https://api.dicebear.com/5.x/personas/svg?seed=Snickers&backgroundColor=c27170",
		name: "Aditya",
		message: "publish now",
		date: "yesterday",
		isOnline: true,
		readMessage: true,
	},
	{
		id: 5,
		image: "https://api.dicebear.com/5.x/personas/svg?seed=Abby&backgroundColor=ebbf9a",
		name: "Ahmed Medi",
		message: "Wow really Cool 🔥",
		date: "1:15 AM",
		isOnline: false,
	},
];
